task: AneurysmSeg
logging_folder: logs
ckpt_folder: ckpt
summary_folder: summary
load_best_model: False  # if false, load last. else load best checkpoint
ckpt_file: checkpoint-0245700.pt  # ckpt file name to load. set null to load the latest ckpt

# will be sent to model as kwargs
model:
  filename: GLIA-Net
  classname: GLIANet
  with_global: True  # whether use global positioning network
  global_type: attention_map
  global_out_channels: 2
  in_channels: 3
  out_channels: 2
  num_classes: 2  # usually same to out_channels
  f_maps: [16, 32, 64, 128]
  norm_type: gn  # bn (batch norm), in (instance norm), gn (group norm) or sn (switchable norm)

data:
  features:
    cta_img_file: image
  hu_values: [[0, 100], [100, 200], [200, 800]]  # HU value intervals  for input images. Length should be same as in_channels
  img_spacing: null  # set null if you don't want to change spacing. e.g. [0.5, 0.5, 0.5]
  patch_size: [96, 96, 96]  # depth, width, height
  overlap_step: [48, 48, 48]  # in sliding window data generating method
  num_proc_workers: 3  # number of data pre-processing workers/processes. set 0 to disable multi-processing.


train:
  batch_size: 2  # for each device/gpu
  losses: # first loss is the main loss. this dict will be sent to LossWrapper as kwargs
    - name: ExpLoss   # local segmentation loss
      final_activation: softmax
    - name: SoftmaxCrossEntropyLoss   # global positioning loss
      final_activation: softmax

eval:
  phase: inference  # phase tag to identify different inference runs
  probability_threshold: 0.5  # to generate label mask from probability map
